config/routes.rb
Rails.application.routes.draw do
  get 'main', to: "main#main"
  post 'login', to: "main#login"
  get 'register', to: "main#register"
  post 'register', to: "main#create_user"
  get 'profile/:name', to: "users#profile", as: 'user'
  get 'logout', to: "main#logout"
  get 'feed', to: "users#feed", as: 'feed'
  get 'post', to: "posts#post", as: 'post'
  post 'create_post', to: "posts#create_post"
  get 'follow/:name', to: 'users#follow', as: 'follow'
  get 'unfollow/:name', to: 'users#unfollow', as: 'unfollow'
  post 'following/:name', to: 'users#following', as: 'following'
  post 'liking/:post', to: 'users#liking', as: 'liking'
  get 'liked_user', to: 'posts#liked_user', as: 'liked_user'
  # resources user
  get '/users(.:format)', to: 'users#index', as: 'users'
  get '/users/new(.:format)', to: 'users#new', as: 'new_user'
  get '/user/:id(.:format)', to: 'users#show', as: 'show_user'
  get '/user/:id/edit(.:format)', to: 'users#edit', as: 'edit_user'
  patch '/users/:id(.:format)', to: 'users#update'
  put '/users/:id(.:format)', to: 'users#update'
  delete '/users/:id(.:format)', to: 'users#destroy', as: 'destroy_user'
  # resources post
  get '/posts(.:format)', to: 'posts#index', as: 'posts'
  get '/posts/new(.:format)', to: 'posts#new', as: 'new_post'
  get '/posts/:id(.:format)', to: 'posts#show', as: 'show_post'
  get '/posts/:id/edit(.:format)', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id(.:format)', to: 'posts#update'
  put '/posts/:id(.:format)', to: 'posts#update'
  delete '/posts/:id(.:format)', to: 'posts#destroy', as: 'destroy_post'
  # resources like
  get '/likes(.:format)', to: 'likes#index', as: 'likes'
  get '/likes/new(.:format)', to: 'likes#new', as: 'new_like'
  get '/likes/:id(.:format)', to: 'likes#show', as: 'show_like'
  get '/likes/:id/edit(.:format)', to: 'likes#edit', as: 'edit_like'
  patch '/likes/:id(.:format)', to: 'likes#update'
  put '/likes/:id(.:format)', to: 'likes#update'
  delete '/likes/:id(.:format)', to: 'likes#destroy', as: 'destroy_like'

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  include MainConcern

  before_action :set_like, only: %i[ show edit update destroy ]
  before_action :check_login, only: %i[ index show edit destroy ]
  before_action :set_user_session, only: %i[ index show edit destroy ]

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: "Like was successfully created." }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: "Like was successfully updated." }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: "Like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:post_id, :user_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@like) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :post
    = f.association :user

  .form-actions
    = f.button :submit

app/views/likes/edit.html.haml
%h1 Editing like

= render 'form'

= link_to 'Show', @like
\|
= link_to 'Back', likes_path

app/views/likes/index.html.haml
%h1 Listing likes

%table#table
  %thead
    %tr
      %th Post
      %th User
      %th
      %th
      %th

  %tbody
    - @likes.each do |like|
      %tr
        %td= like.post
        %td= like.user
        %td= link_to 'Show', show_like_path(like)
        %td= link_to 'Edit', edit_like_path(like)
        %td= link_to 'Destroy', destroy_like_path(like), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Like', new_like_path

app/views/likes/new.html.haml
%h1 New like

= render 'form'

= link_to 'Back', likes_path

app/views/likes/show.html.haml
%p#notice= notice

%p
  %b Post:
  = @like.post
%p
  %b User:
  = @like.user

= link_to 'Edit', edit_like_path(@like)
\|
= link_to 'Back', likes_path