config/routes.rb
Rails.application.routes.draw do
  get 'main', to: "main#main"
  post 'login', to: "main#login"
  get 'register', to: "main#register"
  post 'register', to: "main#create_user"
  get 'profile/:name', to: "users#profile", as: 'user'
  get 'logout', to: "main#logout"
  get 'feed', to: "users#feed", as: 'feed'
  get 'post', to: "posts#post", as: 'post'
  post 'create_post', to: "posts#create_post"
  get 'follow/:name', to: 'users#follow', as: 'follow'
  get 'unfollow/:name', to: 'users#unfollow', as: 'unfollow'
  post 'following/:name', to: 'users#following', as: 'following'
  post 'liking/:post', to: 'users#liking', as: 'liking'
  get 'liked_user', to: 'posts#liked_user', as: 'liked_user'
  # resources user
  get '/users(.:format)', to: 'users#index', as: 'users'
  get '/users/new(.:format)', to: 'users#new', as: 'new_user'
  get '/user/:id(.:format)', to: 'users#show', as: 'show_user'
  get '/user/:id/edit(.:format)', to: 'users#edit', as: 'edit_user'
  patch '/users/:id(.:format)', to: 'users#update'
  put '/users/:id(.:format)', to: 'users#update'
  delete '/users/:id(.:format)', to: 'users#destroy', as: 'destroy_user'
  # resources post
  get '/posts(.:format)', to: 'posts#index', as: 'posts'
  get '/posts/new(.:format)', to: 'posts#new', as: 'new_post'
  get '/posts/:id(.:format)', to: 'posts#show', as: 'show_post'
  get '/posts/:id/edit(.:format)', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id(.:format)', to: 'posts#update'
  put '/posts/:id(.:format)', to: 'posts#update'
  delete '/posts/:id(.:format)', to: 'posts#destroy', as: 'destroy_post'
  # resources like
  get '/likes(.:format)', to: 'likes#index', as: 'likes'
  get '/likes/new(.:format)', to: 'likes#new', as: 'new_like'
  get '/likes/:id(.:format)', to: 'likes#show', as: 'show_like'
  get '/likes/:id/edit(.:format)', to: 'likes#edit', as: 'edit_like'
  patch '/likes/:id(.:format)', to: 'likes#update'
  put '/likes/:id(.:format)', to: 'likes#update'
  delete '/likes/:id(.:format)', to: 'likes#destroy', as: 'destroy_like'

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	has_many :posts
	validates(:email, length: {minimum: 2}, uniqueness: true)
	validates(:name, length: {minimum: 2}, uniqueness: true)
	validates(:password, length: {minimum: 8})
	has_many :followee, class_name: 'Follow', foreign_key: 'followee_id'
	has_many :follower, class_name: 'Follow', foreign_key: 'follower_id'
	validates_confirmation_of :password
	has_many :likes

	def get_feed_post
		return Post.where(:user_id => Follow.where(follower_id:id).pluck('followee_id')).order("created_at DESC")
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include MainConcern
  helper_method :is_like

  before_action :set_user_old, only: %i[ show edit update destroy ]
  before_action :check_login, only: %i[ profile feed follow unfollow index show edit ]
  before_action :set_user_session, only: %i[ profile feed follow unfollow following liking index show edit ]
  before_action :sef_profile, only: %i[ profile follow unfollow following ]

  def profile
    # @profile = User.find_by(name: params[:name])
    # @user = User.find(session[:user_id])
    # @is_follow = Follow.find_by(follower_id:@user.id,followee_id:@profile.id)
    @is_follow = is_follow
    @all_post = @profile.posts
    @all_post = @all_post.sort_by{ |obj| obj.created_at }.reverse!
  end

  def feed
    # @all_followee = @user.follower.map{ |follow| follow.followee_id }
    # @all_post = Post.where(user_id:@all_followee).order('created_at DESC')
    @all_post = @user.get_feed_post
  end

  def following
    if(params[:commit]=='Follow')
      Follow.create(follower:@user,followee:@profile).save
      respond_to do |format|
        format.html { redirect_to feed_path, notice: "Follow "+@profile.name+" successfully" }
      end
    elsif(params[:commit]=='Unfollow')
      Follow.find_by(follower:@user,followee:@profile).destroy
      respond_to do |format|
        format.html { redirect_to feed_path, notice: "Unfollow "+@profile.name+" successfully" }
      end
    end
  end

  def liking
    @post = Post.find(params[:post])
    if(params[:commit]=='Like')
      Like.create(user:@user,post:@post).save
    elsif(params[:commit]=='Unlike')
      Like.find_by(user:@user,post:@post).destroy
    end
    redirect_to feed_path
  end

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def sef_profile
      @profile = User.find_by(name: params[:name])
    end

    def is_follow
      return (@user!=@profile) && (Follow.find_by(follower_id:@user.id,followee_id:@profile.id)!=nil)
    end

    # def is_like
    #   return Like.find_by(user_id:@user.id,post_id:@post)!=nil
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_user_old
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password_digest)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@user) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :email
    = f.input :password_digest

  .form-actions
    = f.button :submit

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/feed.html.haml
%h1 Feed

.div{class:[notice && "alert alert-success"]}
  = notice
.div{class:[alert && "alert alert-danger"]}
  = alert

= link_to 'Create Post', '/post', class:"btn btn-dark mt-2"

= render 'layouts/allpost'

app/views/users/index.html.haml
%h1 Listing users

%table#table
  %thead
    %tr
      %th Name
      %th Email
      %th Password digest
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= user.password_digest
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', destroy_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/profile.html.haml
%h1 Profile

.div{class:[notice && "alert alert-success"]}
  = notice
.div{class:[alert && "alert alert-danger"]}
  = alert

%h5
  %b Name:
  = @profile.name
%h5
  %b Email:
  = @profile.email

= simple_form_for(@user, method: :post, url: following_path(@profile.name)) do |f|
  .form-actions
    -if (@profile!=@user && @is_follow)
      = f.button :submit,'Unfollow',class:'btn btn-outline-danger mt-2',action:'Unfollow'
    -elsif (@profile!=@user && !@is_follow)
      = f.button :submit,'Follow',class:'btn btn-outline-success mt-2',action:'Follow'

= render 'layouts/allpost'

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  %b Password digest:
  = @user.password_digest

/ = link_to 'Edit', edit_user_path(@user)
/ \|
/ = link_to 'Back', users_path