config/routes.rb
Rails.application.routes.draw do
  get 'main', to: "main#main"
  post 'login', to: "main#login"
  get 'register', to: "main#register"
  post 'register', to: "main#create_user"
  get 'profile/:name', to: "users#profile", as: 'user'
  get 'logout', to: "main#logout"
  get 'feed', to: "users#feed", as: 'feed'
  get 'post', to: "posts#post", as: 'post'
  post 'create_post', to: "posts#create_post"
  get 'follow/:name', to: 'users#follow', as: 'follow'
  get 'unfollow/:name', to: 'users#unfollow', as: 'unfollow'
  post 'following/:name', to: 'users#following', as: 'following'
  post 'liking/:post', to: 'users#liking', as: 'liking'
  get 'liked_user', to: 'posts#liked_user', as: 'liked_user'
  # resources user
  get '/users(.:format)', to: 'users#index', as: 'users'
  get '/users/new(.:format)', to: 'users#new', as: 'new_user'
  get '/user/:id(.:format)', to: 'users#show', as: 'show_user'
  get '/user/:id/edit(.:format)', to: 'users#edit', as: 'edit_user'
  patch '/users/:id(.:format)', to: 'users#update'
  put '/users/:id(.:format)', to: 'users#update'
  delete '/users/:id(.:format)', to: 'users#destroy', as: 'destroy_user'
  # resources post
  get '/posts(.:format)', to: 'posts#index', as: 'posts'
  get '/posts/new(.:format)', to: 'posts#new', as: 'new_post'
  get '/posts/:id(.:format)', to: 'posts#show', as: 'show_post'
  get '/posts/:id/edit(.:format)', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id(.:format)', to: 'posts#update'
  put '/posts/:id(.:format)', to: 'posts#update'
  delete '/posts/:id(.:format)', to: 'posts#destroy', as: 'destroy_post'
  # resources like
  get '/likes(.:format)', to: 'likes#index', as: 'likes'
  get '/likes/new(.:format)', to: 'likes#new', as: 'new_like'
  get '/likes/:id(.:format)', to: 'likes#show', as: 'show_like'
  get '/likes/:id/edit(.:format)', to: 'likes#edit', as: 'edit_like'
  patch '/likes/:id(.:format)', to: 'likes#update'
  put '/likes/:id(.:format)', to: 'likes#update'
  delete '/likes/:id(.:format)', to: 'likes#destroy', as: 'destroy_like'

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates(:msg, presence: true)
  has_many :likes

  def get_likers
    # return self.likes.map{ |like| like.user.name }.join(" ")
    # return User.where(:id => self.likes.pluck('user_id')).pluck('name').join(" ")
    return self.likes.joins(:user).pluck('name').join(" ")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include MainConcern

  skip_before_action :verify_authenticity_token

  before_action :check_login, only: %i[ ]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :check_login, only: %i[ index show edit destroy ]
  before_action :set_user_session, only: %i[ post create_post index show edit destroy ]

  def liked_user
  end
  
  def post
    @post = Post.new
  end

  def create_post
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]

    if @post.save
      redirect_to feed_path, notice: "Posted!."
    else
      render :post, status: :unprocessable_entity
    end
  end

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # params.require(:post).permit(:msg, :user_id)
      params.require(:post).permit(:msg)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :msg
    = f.association :user

  .form-actions
    = f.button :submit

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table#table
  %thead
    %tr
      %th Msg
      %th User
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.msg
        %td= post.user
        %td= link_to 'Show', show_post_path(post)
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', destroy_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/post.html.haml
%h1
  = "Let's Post"

= simple_form_for @post, url: 'create_post', method: :post do |f|

  .form-inputs.col-sm-12
    = f.text_area :msg, type: "text", label: false, placeholder: "Say something ...", class:"form-control"

  .form-actions
    = f.button :submit, 'Post', class:"btn btn-dark mt-2"
    = link_to 'Cancel', feed_path, class:"btn btn-outline-dark mt-2"

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Msg:
  = @post.msg
%p
  %b User:
  = @post.user

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path