config/routes.rb
Rails.application.routes.draw do
  get 'main', to: "main#main"
  post 'login', to: "main#login"
  get 'register', to: "main#register"
  post 'register', to: "main#create_user"
  get 'profile/:name', to: "users#profile", as: 'user'
  get 'logout', to: "main#logout"
  get 'feed', to: "users#feed", as: 'feed'
  get 'post', to: "posts#post", as: 'post'
  post 'create_post', to: "posts#create_post"
  get 'follow/:name', to: 'users#follow', as: 'follow'
  get 'unfollow/:name', to: 'users#unfollow', as: 'unfollow'
  post 'following/:name', to: 'users#following', as: 'following'
  post 'liking/:post', to: 'users#liking', as: 'liking'
  get 'liked_user', to: 'posts#liked_user', as: 'liked_user'
  # resources user
  get '/users(.:format)', to: 'users#index', as: 'users'
  get '/users/new(.:format)', to: 'users#new', as: 'new_user'
  get '/user/:id(.:format)', to: 'users#show', as: 'show_user'
  get '/user/:id/edit(.:format)', to: 'users#edit', as: 'edit_user'
  patch '/users/:id(.:format)', to: 'users#update'
  put '/users/:id(.:format)', to: 'users#update'
  delete '/users/:id(.:format)', to: 'users#destroy', as: 'destroy_user'
  # resources post
  get '/posts(.:format)', to: 'posts#index', as: 'posts'
  get '/posts/new(.:format)', to: 'posts#new', as: 'new_post'
  get '/posts/:id(.:format)', to: 'posts#show', as: 'show_post'
  get '/posts/:id/edit(.:format)', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id(.:format)', to: 'posts#update'
  put '/posts/:id(.:format)', to: 'posts#update'
  delete '/posts/:id(.:format)', to: 'posts#destroy', as: 'destroy_post'
  # resources like
  get '/likes(.:format)', to: 'likes#index', as: 'likes'
  get '/likes/new(.:format)', to: 'likes#new', as: 'new_like'
  get '/likes/:id(.:format)', to: 'likes#show', as: 'show_like'
  get '/likes/:id/edit(.:format)', to: 'likes#edit', as: 'edit_like'
  patch '/likes/:id(.:format)', to: 'likes#update'
  put '/likes/:id(.:format)', to: 'likes#update'
  delete '/likes/:id(.:format)', to: 'likes#destroy', as: 'destroy_like'

end

app/views/layouts/_allpost.html.haml
= render 'layouts/likemodal'

.card-deck
  - @all_post.each do |post|
    .card.mt-2
      .card-body.h5.card-title
        = post.msg
      .card-footer
        %h6
          = "Posted by"
          = link_to post.user.name, user_path(post.user.name)
        %h6
          = post.likes.count
          - if post.likes.count > 1
            = ' Likes'
          - else
            = ' Like'
          %a.wholikebutton{"data-target" => "#likeModal", "data-toggle" => "modal", :type => "button", "data-likers"=>"#{post.get_likers}"}
            %h6
              = "See who like this post"
        %h6
          = post.created_at.strftime("%b %d, 20%y %k:%M:%S")
        = simple_form_for(@user, method: :post, url: liking_path(post)) do |f|
          .form-actions
            -if post.likes.find { |like| like.user_id == @user.id}
              = f.button :submit,'Unlike',class:'btn btn-outline-danger mt-2',action:'Unlike'
            -else
              = f.button :submit,'Like',class:'btn btn-outline-success mt-2',action:'Like'

app/views/layouts/_likemodal.html.haml
#likeModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "modalTitle", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#modalTitle.modal-title Who like this post
      .modal-body
        %ul.list-group.list-group-flush#likeduser
      .modal-footer
        %button.btn.btn-outline-secondary.closemodalbutton{"data-dismiss" => "modal", :type => "button"} Close


:javascript
  $(document).ready(function() {
    
    $(".wholikebutton").click(function(){
      $('#likeModal').modal("show");
      let likers = $(this).attr("data-likers").split(" ");
        $("#likeduser").html(likers.map(name => 
        '<li class="list-group-item" data-bs-dismiss="modal"><h6><a style="text-decoration: none;" href="/profile/'+name+'">'+name+'</a></h6></li>'
      ))
    });

    $(".closemodalbutton").click(function(){
      $('#likeModal').modal("hide");
    });

  })

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{href: main_path} Twittee
    - if session[:user_id]
      %span.navbar-brand Hi ! #{@user.name}
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
      - if session[:user_id]
        / .nav-item
        /   %a.btn.btn-outline-dark.d-flex.me-2{:href => "/feed"} Feed
        .nav-item
          %a.btn.btn-outline-dark.d-flex.me-2{:href => user_path(@user.name)} Profile
        .nav-item
          %a.btn.btn-outline-danger.d-flex{:href => "/logout"} Log Out

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Project
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    %link{href:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css", rel:"stylesheet", integrity:"sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF", crossorigin:"anonymous"}
    %script{src:"https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js", integrity:"sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ", crossorigin:"anonymous"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{src:"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"}
    %link{rel:"stylesheet", type:"text/css", href:"https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.css"}
    %script{type:"text/javascript", src:"https://cdn.datatables.net/v/bs5/dt-1.11.3/datatables.min.js"}
  %body
    = render '/layouts/navigation'
    .container
      = yield

:javascript
  $(document).ready( function () {
    $('#table').DataTable();
  } );